// src/components/mode-toggle.tsx
'use client'

import { Moon, Sun } from 'lucide-react'
import { useTheme } from 'next-themes'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from '@/components/ui/dropdown-menu'

export function ModeToggle() {
  const { setTheme } = useTheme()

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="icon">
          <Sun className="h-[1.2rem] w-[1.2rem] scale-100 rotate-0 transition-all dark:scale-0 dark:-rotate-90" />
          <Moon className="absolute h-[1.2rem] w-[1.2rem] scale-0 rotate-90 transition-all dark:scale-100 dark:rotate-0" />
          <span className="sr-only">Toggle theme</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={() => setTheme('light')}>
          Light
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme('dark')}>
          Dark
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => setTheme('system')}>
          System
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// app/components/ModeToggle.vue
<script setup lang="ts">
import type { DropdownMenuItem } from '@nuxt/ui'

const colorMode = useColorMode()

const items: DropdownMenuItem[] = [
  { label: 'Light', icon: 'i-lucide-sun', onSelect: () => (colorMode.preference = 'light') },
  { label: 'Dark', icon: 'i-lucide-moon', onSelect: () => (colorMode.preference = 'dark') },
  {
    label: 'System',
    icon: 'i-lucide-monitor',
    onSelect: () => (colorMode.preference = 'system')
  }
]
</script>

<template>
  <UDropdownMenu :items="items" :content="{ align: 'end' }">
    <UButton
      color="neutral"
      variant="outline"
      size="sm"
      square
      aria-label="Toggle theme"
    >
      <UIcon name="i-lucide-sun" class="size-5 dark:hidden" />
      <UIcon name="i-lucide-moon" class="hidden size-5 dark:block" />
    </UButton>
  </UDropdownMenu>
</template>
