// src/components/nav-user.tsx
'use client'

import { Fragment } from 'react'
import {
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  CreditCard,
  LogOut,
  Sparkles,
  type LucideIcon
} from 'lucide-react'

import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from '@/components/ui/dropdown-menu'
import {
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar
} from '@/components/ui/sidebar'
import { logout } from '@/components/auth/actions'

export function NavUser({
  user
}: {
  user: {
    name: string
    email: string
    avatar: string
  }
}) {
  const { isMobile } = useSidebar()

  const initials =
    (user.name || user.email || '?')
      .split(' ')
      .map((part) => part[0])
      .join('')
      .slice(0, 2)
      .toUpperCase() || '?'

  type MenuItem = {
    title: string
    leadingIcon?: LucideIcon
    trailingIcon?: LucideIcon
    onSelect?: () => void
  }

  const groups: MenuItem[][] = [
    [{ title: 'Upgrade to Pro', leadingIcon: Sparkles }],
    [
      { title: 'Account', leadingIcon: BadgeCheck },
      { title: 'Billing', leadingIcon: CreditCard },
      { title: 'Notifications', leadingIcon: Bell }
    ],
    [{ title: 'Log out', leadingIcon: LogOut, onSelect: () => logout() }]
  ]

  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <SidebarMenuButton
              size="lg"
              className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
            >
              <Avatar className="h-8 w-8 rounded-lg">
                <AvatarImage src={user.avatar} alt={user.name} />
                <AvatarFallback className="rounded-lg">
                  {initials}
                </AvatarFallback>
              </Avatar>
              <div className="grid flex-1 text-left text-sm leading-tight">
                <span className="truncate font-medium">{user.name}</span>
                <span className="truncate text-xs">{user.email}</span>
              </div>
              <ChevronsUpDown className="ml-auto size-4" />
            </SidebarMenuButton>
          </DropdownMenuTrigger>
          <DropdownMenuContent
            className="w-(--radix-dropdown-menu-trigger-width) min-w-56 rounded-lg"
            side={isMobile ? 'bottom' : 'top'}
            align="end"
            sideOffset={4}
          >
            <DropdownMenuLabel className="p-0 font-normal">
              <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                <Avatar className="h-8 w-8 rounded-lg">
                  <AvatarImage src={user.avatar} alt={user.name} />
                  <AvatarFallback className="rounded-lg">
                    {initials}
                  </AvatarFallback>
                </Avatar>
                <div className="grid flex-1 text-left text-sm leading-tight">
                  <span className="truncate font-medium">{user.name}</span>
                  <span className="truncate text-xs">{user.email}</span>
                </div>
              </div>
            </DropdownMenuLabel>
            {groups.map((group, index) => (
              <Fragment key={index}>
                <DropdownMenuSeparator />
                <DropdownMenuGroup>
                  {group.map((child) => (
                    <DropdownMenuItem
                      key={child.title}
                      onSelect={child.onSelect}
                    >
                      {child.leadingIcon && <child.leadingIcon />}
                      {child.title}
                      {child.trailingIcon && (
                        <child.trailingIcon className="ms-auto" />
                      )}
                    </DropdownMenuItem>
                  ))}
                </DropdownMenuGroup>
              </Fragment>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  )
}

// app/components/sidebar/NavUser.vue
<script setup lang="ts">
import type { DropdownMenuItem } from '@nuxt/ui'

const props = defineProps<{
  user: { name: string; email: string; avatar: string }
}>()

const colorMode = useColorMode()
const { clear } = useUserSession()

const initials = computed(() => {
  const source = props.user.name || props.user.email || '?'
  return (
    source
      .split(' ')
      .map((p) => p[0])
      .join('')
      .slice(0, 2)
      .toUpperCase() || '?'
  )
})

async function logout() {
  await clear()
  await navigateTo('/login')
}

const items = computed<DropdownMenuItem[][]>(() => [
  [
    {
      label: 'Light',
      icon: 'i-lucide-sun',
      type: 'checkbox' as const,
      checked: colorMode.preference === 'light',
      onUpdateChecked: () => (colorMode.preference = 'light')
    },
    {
      label: 'Dark',
      icon: 'i-lucide-moon',
      type: 'checkbox' as const,
      checked: colorMode.preference === 'dark',
      onUpdateChecked: () => (colorMode.preference = 'dark')
    },
    {
      label: 'System',
      icon: 'i-lucide-sparkles',
      type: 'checkbox' as const,
      checked: colorMode.preference === 'system',
      onUpdateChecked: () => (colorMode.preference = 'system')
    }
  ],
  [{ label: 'Log out', icon: 'i-lucide-log-out', onSelect: logout }]
])
</script>

<template>
  <UDropdownMenu
    :items="items"
    :content="{ align: 'end', side: 'top' }"
    :ui="{ content: 'min-w-56' }"
  >
    <button
      class="flex w-full items-center gap-2 rounded-md p-2 text-left hover:bg-sidebar-accent/60"
    >
      <UAvatar :src="user.avatar || undefined" :alt="user.name" :text="initials" size="sm" />
      <div class="grid flex-1 text-sm leading-tight">
        <span class="truncate font-medium">{{ user.name }}</span>
        <span class="truncate text-xs text-muted-foreground">{{ user.email }}</span>
      </div>
      <UIcon name="i-lucide-chevrons-up-down" class="ml-auto size-4" />
    </button>
  </UDropdownMenu>
</template>
