// src/components/auth/resend-button.tsx
'use client'

import { useActionState } from 'react'

import { resendMagicLink, type ActionState } from '@/components/auth/actions'
import { FieldDescription } from '@/components/ui/field'

type ResendButtonProps = {
  email: string
  redirectTo?: string
}

export function ResendButton({ email, redirectTo }: ResendButtonProps) {
  const initialState: ActionState = { ok: false, error: null }
  const [state, formAction, pending] = useActionState(
    resendMagicLink,
    initialState
  )

  return (
    <form action={formAction}>
      <input type="hidden" name="email" value={email} />
      {redirectTo ? (
        <input type="hidden" name="redirectTo" value={redirectTo} />
      ) : null}
      <FieldDescription>
        Didn&apos;t get the mail?{' '}
        <button
          type="submit"
          disabled={pending}
          className="font-medium underline underline-offset-4 hover:text-primary disabled:opacity-50"
        >
          {pending ? 'Sending…' : 'Resend'}
        </button>
      </FieldDescription>
      {state.ok ? (
        <FieldDescription className="mt-2 text-primary">
          A new link is on its way to you.
        </FieldDescription>
      ) : null}
      {state.error ? (
        <FieldDescription className="mt-2 text-destructive">
          {state.error}
        </FieldDescription>
      ) : null}
    </form>
  )
}

// app/components/auth/ResendButton.vue
<script setup lang="ts">
const props = defineProps<{ email: string, redirectTo?: string }>()

const pending = ref(false)
const sent = ref(false)
const error = ref<string | null>(null)

async function resend() {
  error.value = null
  sent.value = false
  pending.value = true
  try {
    await $fetch('/api/auth/magic-link', {
      method: 'POST',
      body: { email: props.email, redirectTo: props.redirectTo ?? '/' }
    })
    sent.value = true
  } catch (e) {
    const err = e as { data?: { message?: string }, statusMessage?: string }
    error.value = err.data?.message ?? err.statusMessage ?? 'Could not resend.'
  } finally {
    pending.value = false
  }
}
</script>

<template>
  <div>
    <p class="text-sm text-muted-foreground">
      Didn't get the mail?
      <button
        type="button"
        :disabled="pending"
        class="font-medium underline underline-offset-4 hover:text-primary disabled:opacity-50"
        @click="resend"
      >
        {{ pending ? 'Sending…' : 'Resend' }}
      </button>
    </p>
    <p v-if="sent" class="mt-2 text-sm text-primary">
      A new link is on its way to you.
    </p>
    <p v-if="error" class="mt-2 text-sm text-error">
      {{ error }}
    </p>
  </div>
</template>
