// src/app/subscriptions/page.tsx
import { redirect } from 'next/navigation'
import { eq } from 'drizzle-orm'

import { auth } from '@/auth'
import { db } from '@/db'
import { subscriptions } from '@/db/schema'
import { SubscriptionsTable } from '@/components/subscriptions/table'
import { DashboardLayout } from '@/components/dashboard-layout'
import { AddSubscriptionDialog } from '@/components/subscriptions/add-dialog'
import { SubscriptionDataCards } from '@/components/subscriptions/data-cards'

export default async function SubscriptionsPage() {
  const session = await auth()
  if (!session?.user?.id) redirect('/login')

  const subs = await db
    .select()
    .from(subscriptions)
    .where(eq(subscriptions.userId, session.user.id))

  return (
    <DashboardLayout>
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">My subscriptions</h1>
        <AddSubscriptionDialog />
      </div>

      <SubscriptionDataCards subscriptions={subs} />

      <SubscriptionsTable subscriptions={subs} />
    </DashboardLayout>
  )
}

// app/pages/subscriptions.vue
<script setup lang="ts">
import type { Subscription } from '~~/server/db/schema'

definePageMeta({ layout: 'dashboard', middleware: 'auth' })
useHead({ title: 'Subscriptions · Unmyst' })

const { data: subs, refresh } = await useFetch<Subscription[]>('/api/subscriptions', {
  default: () => []
})
</script>

<template>
  <div class="@container/main flex flex-col gap-4 md:gap-6">
    <div class="flex items-center justify-between">
      <h1 class="text-2xl font-bold">My subscriptions</h1>
      <SubscriptionsAddDialog @saved="refresh" />
    </div>

    <SubscriptionsDataCards :subscriptions="subs" />

    <SubscriptionsTable :subscriptions="subs" @refresh="refresh" />
  </div>
</template>
