// app/components/subscriptions/AddDialog.vue
<script setup lang="ts">
const emit = defineEmits<{ saved: [] }>()
const open = ref(false)

function onSuccess() {
  open.value = false
  emit('saved')
}
</script>

<template>
  <UModal
    v-model:open="open"
    title="New Subscription"
    description="Fill out infos about your newly subscribed service and click &quot;Confirm&quot;."
  >
    <UButton icon="i-lucide-plus" color="neutral" variant="outline">
      Add Subscription
    </UButton>

    <template #body>
      <SubscriptionsSubscriptionForm @success="onSuccess">
        <template #cancel>
          <UButton color="neutral" variant="outline" @click="open = false">
            Cancel
          </UButton>
        </template>
      </SubscriptionsSubscriptionForm>
    </template>
  </UModal>
</template>

// src/components/subscriptions/add-dialog.tsx
'use client'

import { useState } from 'react'

import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from '@/components/ui/dialog'
import { SubscriptionForm, SubmitButton } from '@/components/subscriptions/form'
import { PlusIcon } from 'lucide-react'

export function AddSubscriptionDialog() {
  const [open, setOpen] = useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline">
          <PlusIcon />
          Add Subscription
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>New Subscription</DialogTitle>
          <DialogDescription>
            Fill out infos about your newly subscribed service and click
            &quot;Save&quot;
          </DialogDescription>
        </DialogHeader>
        <SubscriptionForm
          onSuccess={() => setOpen(false)}
          footer={
            <DialogFooter className="flex lg:justify-between">
              <DialogClose asChild>
                <Button type="button" variant="outline">
                  Cancel
                </Button>
              </DialogClose>
              <SubmitButton />
            </DialogFooter>
          }
        />
      </DialogContent>
    </Dialog>
  )
}
