// app/components/dashboard/SectionCards.vue
<script setup lang="ts">
// Static demo KPIs (ported from the shadcn dashboard sample). Placeholder data.
const cards = [
  { title: 'Total Revenue', value: '$1,250.00', delta: '+12.5%', up: true, foot: 'Trending up this month', sub: 'Visitors for the last 6 months' },
  { title: 'New Customers', value: '1,234', delta: '-20%', up: false, foot: 'Down 20% this period', sub: 'Acquisition needs attention' },
  { title: 'Active Accounts', value: '45,678', delta: '+12.5%', up: true, foot: 'Strong user retention', sub: 'Engagement exceed targets' },
  { title: 'Growth Rate', value: '4.5%', delta: '+4.5%', up: true, foot: 'Steady performance increase', sub: 'Meets growth projections' }
]
</script>

<template>
  <div class="grid grid-cols-1 gap-4 @xl/main:grid-cols-2 @5xl/main:grid-cols-4">
    <UCard
      v-for="card in cards"
      :key="card.title"
      class="@container/card bg-linear-to-t from-primary/5 to-card"
    >
      <div class="flex items-start justify-between">
        <div class="text-sm text-muted-foreground">{{ card.title }}</div>
        <UBadge variant="outline" color="neutral" size="sm">
          <UIcon :name="card.up ? 'i-lucide-trending-up' : 'i-lucide-trending-down'" />
          {{ card.delta }}
        </UBadge>
      </div>
      <div class="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
        {{ card.value }}
      </div>
      <div class="mt-3 flex flex-col items-start gap-1.5 text-sm">
        <div class="line-clamp-1 flex items-center gap-2 font-medium">
          {{ card.foot }}
          <UIcon :name="card.up ? 'i-lucide-trending-up' : 'i-lucide-trending-down'" class="size-4" />
        </div>
        <div class="text-muted-foreground">{{ card.sub }}</div>
      </div>
    </UCard>
  </div>
</template>

// src/components/dashboard/section-cards.tsx
'use client'

import { TrendingUpIcon, TrendingDownIcon } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import {
  Card,
  CardAction,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from '@/components/ui/card'

export function SectionCards() {
  return (
    <div className="grid grid-cols-1 gap-4 *:data-[slot=card]:bg-linear-to-t *:data-[slot=card]:from-primary/5 *:data-[slot=card]:to-card *:data-[slot=card]:shadow-xs @xl/main:grid-cols-2 @5xl/main:grid-cols-4 dark:*:data-[slot=card]:bg-card">
      <Card className="@container/card">
        <CardHeader>
          <CardDescription>Total Revenue</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            $1,250.00
          </CardTitle>
          <CardAction>
            <Badge variant="outline">
              <TrendingUpIcon />
              +12.5%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Trending up this month <TrendingUpIcon className="size-4" />
          </div>
          <div className="text-muted-foreground">
            Visitors for the last 6 months
          </div>
        </CardFooter>
      </Card>
      <Card className="@container/card">
        <CardHeader>
          <CardDescription>New Customers</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            1,234
          </CardTitle>
          <CardAction>
            <Badge variant="outline">
              <TrendingDownIcon />
              -20%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Down 20% this period <TrendingDownIcon className="size-4" />
          </div>
          <div className="text-muted-foreground">
            Acquisition needs attention
          </div>
        </CardFooter>
      </Card>
      <Card className="@container/card">
        <CardHeader>
          <CardDescription>Active Accounts</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            45,678
          </CardTitle>
          <CardAction>
            <Badge variant="outline">
              <TrendingUpIcon />
              +12.5%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Strong user retention <TrendingUpIcon className="size-4" />
          </div>
          <div className="text-muted-foreground">Engagement exceed targets</div>
        </CardFooter>
      </Card>
      <Card className="@container/card">
        <CardHeader>
          <CardDescription>Growth Rate</CardDescription>
          <CardTitle className="text-2xl font-semibold tabular-nums @[250px]/card:text-3xl">
            4.5%
          </CardTitle>
          <CardAction>
            <Badge variant="outline">
              <TrendingUpIcon />
              +4.5%
            </Badge>
          </CardAction>
        </CardHeader>
        <CardFooter className="flex-col items-start gap-1.5 text-sm">
          <div className="line-clamp-1 flex gap-2 font-medium">
            Steady performance increase <TrendingUpIcon className="size-4" />
          </div>
          <div className="text-muted-foreground">Meets growth projections</div>
        </CardFooter>
      </Card>
    </div>
  )
}
