// app/components/auth/SignupForm.vue
<script setup lang="ts">
// Magic-link auth doesn't distinguish signup from login: the user row is created
// on first verified link, so this posts to the same endpoint and inherits its
// per-IP + per-email rate limiting.
const props = defineProps<{ callbackUrl?: string }>()

const email = ref('')
const error = ref<string | null>(null)
const pending = ref(false)

const redirectTo = computed(() => props.callbackUrl || '/')

async function onSubmit() {
  error.value = null
  pending.value = true
  try {
    await $fetch('/api/auth/magic-link', {
      method: 'POST',
      body: { email: email.value, redirectTo: redirectTo.value }
    })
    await navigateTo({
      path: '/verify-request',
      query: {
        email: email.value,
        ...(redirectTo.value !== '/' ? { redirectTo: redirectTo.value } : {})
      }
    })
  } catch (e) {
    const err = e as { data?: { message?: string }; statusMessage?: string }
    error.value =
      err.data?.message ??
      err.statusMessage ??
      'Something went wrong. Try again.'
  } finally {
    pending.value = false
  }
}
</script>

<template>
  <div class="flex flex-col gap-6">
    <form @submit.prevent="onSubmit">
      <div class="flex flex-col gap-6">
        <div class="flex flex-col items-center gap-2 text-center">
          <NuxtLink to="/" class="flex flex-col items-center gap-2 font-medium">
            <UIcon name="i-lucide-gallery-vertical-end" class="size-6" />
            <span class="sr-only">Unmyst</span>
          </NuxtLink>
          <h1 class="text-xl font-bold">Welcome to Unmyst</h1>
          <p class="text-sm text-muted-foreground">
            Already have an account?
            <NuxtLink
              to="/login"
              class="text-primary underline-offset-4 hover:underline"
            >
              Sign in
            </NuxtLink>
          </p>
        </div>

        <fieldset :disabled="pending" class="flex flex-col gap-2">
          <UFormField label="Email" :error="error ?? undefined" name="email">
            <UInput
              v-model="email"
              type="email"
              placeholder="m@example.com"
              autocomplete="email"
              required
              class="w-full"
            />
          </UFormField>
          <UButton type="submit" block :loading="pending" class="mt-2">
            {{ pending ? 'Sending…' : 'Create Account' }}
          </UButton>
        </fieldset>

        <USeparator label="or" />

        <UButton
          variant="outline"
          color="neutral"
          block
          icon="i-simple-icons-google"
          to="/auth/google"
          external
        >
          Continue with Google
        </UButton>
      </div>
    </form>

    <p class="px-6 text-center text-xs text-muted-foreground">
      By clicking continue, you agree to our
      <a href="#" class="underline underline-offset-4">Terms of Service</a> and
      <a href="#" class="underline underline-offset-4">Privacy Policy</a>.
    </p>
  </div>
</template>

// src/components/auth/signup-form.tsx
'use client'

import { useActionState } from 'react'
import Link from 'next/link'
import { GalleryVerticalEnd } from 'lucide-react'
import { signIn } from 'next-auth/react'

import { cn } from '@/lib/utils'
import { loginWithEmail, type ActionState } from '@/components/auth/actions'
import { Button } from '@/components/ui/button'
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldSeparator
} from '@/components/ui/field'
import { Input } from '@/components/ui/input'
import { PendingFieldset } from '@/components/pending-fieldset'
import { SubmitButton } from '@/components/submit-button'

type SignupFormProps = React.ComponentProps<'div'> & {
  callbackUrl?: string
}

export function SignupForm({
  className,
  callbackUrl,
  ...props
}: SignupFormProps) {
  // Magic-link auth doesn't distinguish signup from login: the Drizzle adapter
  // creates the user on first verified link, so we reuse loginWithEmail and
  // inherit its per-IP + per-email rate limiting for free.
  const initialState: ActionState = { ok: false, error: null }
  const [state, formAction] = useActionState(loginWithEmail, initialState)

  return (
    <div className={cn('flex flex-col gap-6', className)} {...props}>
      <form action={formAction}>
        <input type="hidden" name="redirectTo" value={callbackUrl ?? '/'} />
        <FieldGroup>
          <div className="flex flex-col items-center gap-2 text-center">
            <Link
              href="/"
              className="flex flex-col items-center gap-2 font-medium"
            >
              <div className="flex size-8 items-center justify-center rounded-md">
                <GalleryVerticalEnd className="size-6" />
              </div>
              <span className="sr-only">Unmyst</span>
            </Link>
            <h1 className="text-xl font-bold">Welcome to Unmyst</h1>
            <FieldDescription>
              Already have an account? <a href="/login">Sign in</a>
            </FieldDescription>
          </div>
          <PendingFieldset className="space-y-2">
            <Field>
              <FieldLabel htmlFor="email">Email</FieldLabel>
              <Input
                id="email"
                name="email"
                type="email"
                placeholder="m@example.com"
                required
                aria-invalid={!!state.error}
              />
              <FieldError>{state.error}</FieldError>
            </Field>
            <Field>
              <SubmitButton>Create Account</SubmitButton>
            </Field>
          </PendingFieldset>
          <FieldSeparator>or</FieldSeparator>
          <Field>
            <Button
              variant="outline"
              type="button"
              onClick={() => signIn('google', { redirectTo: callbackUrl ?? '/' })}
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path
                  d="M12.48 10.92v3.28h7.84c-.24 1.84-.853 3.187-1.787 4.133-1.147 1.147-2.933 2.4-6.053 2.4-4.827 0-8.6-3.893-8.6-8.72s3.773-8.72 8.6-8.72c2.6 0 4.507 1.027 5.907 2.347l2.307-2.307C18.747 1.44 16.133 0 12.48 0 5.867 0 .307 5.387.307 12s5.56 12 12.173 12c3.573 0 6.267-1.173 8.373-3.36 2.16-2.16 2.84-5.213 2.84-7.667 0-.76-.053-1.467-.173-2.053H12.48z"
                  fill="currentColor"
                />
              </svg>
              Continue with Google
            </Button>
          </Field>
        </FieldGroup>
      </form>
      <FieldDescription className="px-6 text-center">
        By clicking continue, you agree to our <a href="#">Terms of Service</a>{' '}
        and <a href="#">Privacy Policy</a>.
      </FieldDescription>
    </div>
  )
}
